steps:
  # Check if the directory already exists, if not, clone the repository
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ ! -d "wholesale_dag_examples" ]; then
          git clone https://github.com/Keerthanaakula2/wholesale_dag_examples
        else
          echo "Directory 'wholesale_dag_examples' already exists, skipping clone step."
        fi

  # Install dependencies and run unittest tests for inventory DAG
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd wholesale_dag_examples
        pip install -r requirements.txt
        python -m unittest discover tests -p "test_inventory_dag.py"

  # Install dependencies and run pytest tests for inventory DAG
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd wholesale_dag_examples
        pip install -r requirements.txt
        pip install pytest
        pytest tests/test_inventory_dag_pytest.py

  # Install dependencies and run unittest tests for orders DAG
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd wholesale_dag_examples
        pip install -r requirements.txt
        python -m unittest discover tests -p "test_orders_dag.py"

  # Install dependencies and run pytest tests for orders DAG
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd wholesale_dag_examples
        pip install -r requirements.txt
        pip install pytest
        pytest tests/test_orders_dag_pytest.py

  # ... Other steps for deployment or further testing.
