steps:
  # Check if the directory already exists, if not, clone the repository
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ ! -d "wholesale_dag_examples" ]; then
          git clone https://github.com/Keerthanaakula2/wholesale_dag_examples
        else
          echo "Directory 'wholesale_dag_examples' already exists, skipping clone step."
        fi

  # Run unittest tests
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd wholesale_dag_examples
        python -m unittest discover tests -p "*_unittest.py"

  # Install pytest and run pytest tests
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd wholesale_dag_examples
        pip install pytest
        pytest tests

  # ... Other steps for deployment or further testing.
