steps:
  # Step 1: Cloning the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Keerthanaakula2/wholesale_dag_examples', '.']

  # Step 2: Set up Python virtual environment and install dependencies
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt'

  # Step 3: Run unittest tests
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'source venv/bin/activate && venv/bin/python -m unittest discover tests -p "*_unittest.py"'

  # Step 4: Run pytest tests
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'source venv/bin/activate && venv/bin/pytest tests'